#TODO ==== BUILT WITH QOONITY VERSION-1.0 - YINKA-ANTHONY-NKAY ON 2025-03-20T02:40:52.564719600
version = 0.1
[default.deploy.parameters]
stack_name = "teacherStudentMIS"
resolve_s3 = true
s3_prefix = "teacherStudentMIS"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "SecurityGroupId=\"\" Subnet1Id=\"\" Subnet2Id=\"\" DatabaseSecretName=\"\" DatabaseEndpoint=\"\""
image_repositories = []
profile = "qucoon"

